version: '3.1'
volumes:
  mongo_data:
services:
  mongo:
    container_name: iampeterbanjo_mongodb
    restart: unless-stopped
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 37017:37017
