version: '3.1'
volumes:
  mongo_data:
services:
  mongo:
    container_name: iampeterbanjo-mongodb
    restart: unless-stopped
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
