version: '3.1'
volumes:
  mongo_data:
services:
  iampeterbanjo_mongo:
    container_name: iampeterbanjo_mongodb
    restart: unless-stopped
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 37017:37017

  iampeterbanjo_api:
    container_name: iampeterbanjo_api
    environment:
      NODE_ENV: development
    build:
      context: ../packages/api
      dockerfile: ../../docker/Dockerfile
    volumes:
      - ../packages/api:/usr/src/app
    ports:
      - 8080:8080
